import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Photos",
	description: "Generated by create next app",
};

export default function PhotosLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<main className="p-10 max-w-7xl mx-auto">
			{children}
			{modal}
		</main>
	);
}
